apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # <plural>.<group>
  name: testcases.tke.tencentcloud.com
spec:
  # /apis/<group>/<version>
  group: tke.tencentcloud.com
  # /apis/<group>/<version>
  version: v1
  # Namespaced or Cluster
  scope: Cluster
  names:
    # /apis/<group>/<version>/<plural>
    plural: testcases
    singular: testcase
    kind: TestCase
    shortNames:
      - tc
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            testCaceClass:
              type: string
            image:
              type: string
            commad:
              type: array
              items:
                type: string
  subresources:
    status:
      testCaseNamespace:
        type: string
      testCasePod:
        type: string
      # passed or failed
      result:
        type: string
      errMsg:
        type: string
      completeTime:
        type: date-time

