apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # <plural>.<group>
  name: summarys.tke.tencentcloud.com
spec:
  # /apis/<group>/<version>
  group: tke.tencentcloud.com
  # /apis/<group>/<version>
  version: v1
  # Namespaced or Cluster
  scope: Cluster
  names:
    # /apis/<group>/<version>/<plural>
    plural: summarys
    singular: summary
    kind: Summary
    shortNames:
      - summ
  subresources:
    status:
      totalNumber:
        type: int
      passedNumber:
        type: int
      failedNumber:
        type: int